
modLoader="javafml"

loaderVersion="[28,)"

issueTrackerURL="https://github.com/WhoCraft/WhoCosmetics/issues"
[[mods]]
modId="whocosmetics"
version="${mod_version}"
displayName="Who Cosmetics"
#updateJSONURL="http://myurl.me/"
#displayURL="http://example.com/"
logoFile="whocosmetics.png"

authors="Swirtzly, BellatorHD, 50ap5ud5"
credits="EndPhoenix, Violet, Vespa, ItzAngela"
description='''
Adds different clothing from the popular television series, Doctor Who'''

[[dependencies.whocosmetics]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"

    side="BOTH"

[[dependencies.whocosmetics]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
